### ISSUE TITLE
Add known issue for upgrading app starters from Celcius to more recent versions

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#112]
Although this is an issue in OSS it can manifest itself for users of the tile service instances. Here are the reproduction steps to inform the documentation for this (not to put these steps into the docs):

```
Repro steps:
1.  Install SCDF 1.3.3 on PCF 2.5
2. Create scdf service instance
3. shell in and import Celsius apps
4. create basic `http|httpclient|log` stream
5. deploy stream
6. run stream to verify success
7. upgrade SCDF for PCF tile from 1.3.3 to 1.4
8. run `cf update-service...` for scdf service instance
9. `app import` latest version of apps
10. Set default app version for `http`, `httpclient`, `log` to latest
11. Update stream
12. Get back `HTTP 500` (edited)
```

This can result in the following error:

```
[nio-8080-exec-5] o.s.c.d.s.c.RestControllerAdvice : Caught exception while handling a request
2019-06-24T13:50:36.111-04:00 [RTR/1] [OUT] dataflow-[GUID].[DOMAIN] - [DATE/TIME] "POST /streams/deployments/update/willupgrade HTTP/1.1" 500 202 72 "-" "Apache-HttpClient/4.5.6 (Java/1.8.0_202)" 
```

**Comment by fifthposition** [comment]
What are the relevant Pivotal SCDF tile versions? I note that the steps mention upgrading the tile from 1.3.x to 1.4.x, and the latest tile version is 1.6. Going through our documentation from 1.6 back to 1.3, I don't see any direct mention of "Celsius".

**Comment by csterwa** [comment]
This is only on `1.3.x` and for the specific versions of Pivotal SCDF tile 1.3.3 and PCF 2.5.x.

**Comment by fifthposition** [comment]
Up here (first known issue in the list): https://docs-pcf-staging.cfapps.io/scdf/1-3/release-notes.html#known-issues
