### ISSUE TITLE
Tile configuration for Maven repositories in 1.5.1

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#113]
Operators our now able to configure Maven repositories in the tile, including credentials, that are applied to all `p-dataflow` service instances.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-5/tile-configuration.html#configure-default-maven-repositories.

**Comment by csterwa** [comment]
@fifthposition this looks great although I think the screenshot will need to be updated once the required `*` is properly displaying (or not displaying) on fields.

**Comment by fifthposition** [comment]
I updated the screenshot (edited in Preview) @csterwa -- does it work now? http://docs-pcf-staging.cfapps.io/scdf/1-5/tile-configuration.html#configure-default-maven-repositories

**Comment by csterwa** [comment]
The screen changed more than just removing the `*` unfortunately @fifthposition. We'll need to block this until the changes get resolved. Or ask @mheath for an environment where this shows properly?

**Comment by csterwa** [comment]
@fifthposition it looks like the required indicator issue is actually a bug in early versions of Ops Manager 2.5.x. Therefore, you'll need to find an environment (maybe from @mheath ) that has a version without this bug in OM. Let me know if you need additional help. Please update the screenshot with new text. Thanks.

**Comment by fifthposition** [comment]
This is up at https://docs-pcf-staging.cfapps.io/scdf/1-5/tile-configuration.html#configure-default-maven-repositories.
