### ISSUE TITLE
Add arbitrary service instances to bindings for deployed applications

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#114]
When a `p-dataflow` service instance is created like the following:

`cf cs p-dataflow standard data-flow -c '{"services": [ "config-server", ... ]}'`

Then when streams and tasks are deployed, the resulting applications will be bound the services with names provided in the `services` array.

This is for 1.5.1.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-5/managing-service-instances.html#binding-arbitrary-services.
