### ISSUE TITLE
Rebrand to Pivotal Spring Cloud Data Flow as product name

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#118]
As part of our rebranding effort away from a suffix of `for PCF` towards prefixing with `Pivotal ...` on all products, we need to update our docs to reflect this change.

**Comment by fifthposition** [comment]
* 1.6: https://docs-pcf-staging.cfapps.io/scdf/1-6/
* 1.5: http://docs-pcf-staging.cfapps.io/scdf/1-5/
* 1.4: http://docs-pcf-staging.cfapps.io/scdf/1-4/
