### ISSUE TITLE
Update Getting Started guide

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#122]
Screenshots and other content may be out of date. Please run through Getting Started and update as necessary.

https://docs.pivotal.io/scdf/1-6/getting-started.html

**Comment by fifthposition** [comment]
This is at https://docs-pcf-staging.cfapps.io/scdf/1-6/getting-started.html

@csterwa It's only updated for Pivotal SCDF 1.6--not sure how far back the UI update goes in tile versions but let me know if I should backport for earlier tile versions.
