### ISSUE TITLE
Stemcell changed to Xenial 315.* in 1.6.2+ releases

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#124]
It seems that the Xenial stemcell was changed when Pivotal SCDF 1.6.2 was released from 250.* to 315.*. Can we post this in the release notes and anywhere else that the stemcell is mentioned?

**Comment by fifthposition** [comment]
I don't know the exact stemcell that 1.6.2 uses, but we now note that we use `315.*`. Added to release notes; we don't mention the stemcell version anywhere else in the docs.

**Comment by csterwa** [comment]
Sorry @fifthposition I didn't even look at the release notes cause I thought I had missed it. Looks like I knew about it. I am going to close this.
