### ISSUE TITLE
Update screenshots throughout 1.6 docs

### ISSUE THREAD

**Issue by fifthposition** [pivotal-cf/docs-spring-cloud-dataflow#125]

**Comment by fifthposition** [comment]
Actually ended up just removing screenshots from these pages:

* https://docs-pcf-staging.cfapps.io/scdf/1-6/service-broker-and-instances.html
* https://docs-pcf-staging.cfapps.io/scdf/1-6/using-the-dashboard.html

(They were of Apps Manager, and we do describe how to navigate to apps or the dashboard through Apps Manager, but there's no need to keep screenshots of it IMO.)

@csterwa @royclarkson

**Comment by csterwa** [comment]
Good idea. I don't think we should post screenshots that are not part of our product directly.
