### ISSUE TITLE
Add example for using custom service plans

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#128]
In the section "Setting Dependent Services", an example command that sets the data services would be helpful:

https://docs.pivotal.io/scdf/1-6/managing-service-instances.html#setting-dependent-services

```
$ $ cf create-service p-dataflow standard data-flow -c '{ "relational-data-service": { "name": "p.mysql", "plan": "med-db"}, "messaging-data-service": { "name": "p.rabbitmq", "plan": "high-vol" }, "skipper-relational": { "name": "p.mysql", "plan": "sm-db" } }'
```

**Comment by fifthposition** [comment]
See https://docs-pcf-staging.cfapps.io/scdf/1-6/managing-service-instances.html#setting-dependent-services
