### ISSUE TITLE
Update PCF version in Product Snapshot table

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#129]
There is a typo for compatible PAS versions at https://docs.pivotal.io/scdf/1-6/index.html. This should show PAS 2.4.x and higher or at least go up to most recent PAS version 2.7.x.

**Comment by fifthposition** [comment]
To be clear: Ops Manager already says v2.4–v2.7. This is just to update PAS to v2.4–v2.7?

**Comment by csterwa** [comment]
Yes

**Comment by fifthposition** [comment]
See https://docs-pcf-staging.cfapps.io/scdf/1-6/#snapshot
