### ISSUE TITLE
No instruction to setup Network

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-spring-cloud-dataflow#13]
Im trying to install SCDF on AWS + PCF 2.0.
I downloaded and added SCDF tile on the PCF ops manager. 
The documentation doesn't tell which network is to be selected. 
The network dropdown shows Management network and ERT network. Which one is correct network? 
The docs skips the network setup tab completely.

**Comment by csterwa** [comment]
@msathe-tech SCDF for PCF uses the ERT network. We'll review the docs to update this. Thank you.
