### ISSUE TITLE
Add "one-step upgrade" as a key feature of using the tile

### ISSUE THREAD

**Issue by mheath** [pivotal-cf/docs-spring-cloud-dataflow#133]

**Comment by fifthposition** [comment]
Added: https://docs-pcf-staging.cfapps.io/scdf/1-6/#features

**Comment by csterwa** [comment]
Should these features link to their doc references?

**Comment by fifthposition** [comment]
I'm not sure every one has a clear docs reference. e.g "Addition of the Spring Cloud Data Flow server to the Marketplace as a managed service", "Integration of Data Flow server with PCF's UAA security model"

**Comment by csterwa** [comment]
Can you link those that do? I think marketplace can be linked to managing service instances.

**Comment by fifthposition** [comment]
Done: https://docs-pcf-staging.cfapps.io/scdf/1-6/index.html#features Let me know if that works.
