### ISSUE TITLE
Skipper relational database settings missing in user-provides services section

### ISSUE THREAD

**Issue by mheath** [pivotal-cf/docs-spring-cloud-dataflow#134]
Just like `relational-data-service`, you can specify the database service instance used by Skipper using `skipper-relational` as a configuration parameter.

**Comment by fifthposition** [comment]
Added a section to "Using User-Provided Service Instances": https://docs-pcf-staging.cfapps.io/scdf/1-6/using-user-provided-service-instances.html#skipper-relational-database-service
