### ISSUE TITLE
Missing app setting configuration parameters

### ISSUE THREAD

**Issue by mheath** [pivotal-cf/docs-spring-cloud-dataflow#135]
The memory and disk can be configured for both SCDF and Skipper.

For example:

`-c "{"dataflow.disk": DISK_IN_MB}"` - sets disk used by SCDF server
`-c "{"dataflow.memory": MEM_IN_MB}"` - set memory used by SCDF server
`-c "{"skipper.disk": DISK_IN_MB}"` - sets disk used by Skipper
`-c "{"skipper.memory": MEM_IN_MB}"` - set memory used by Skipper

**Comment by fifthposition** [comment]
Added section: https://docs-pcf-staging.cfapps.io/scdf/1-6/managing-service-instances.html#server-and-skipper-app-settings
