### ISSUE TITLE
Missing "maven-cache" parameter

### ISSUE THREAD

**Issue by mheath** [pivotal-cf/docs-spring-cloud-dataflow#137]
By default we disable the caching of artifacts downloaded from a Maven repository because it fills up the app container too quickly causing SCDF and/or Skipper to fail. You can enable this if you want using `-c "{"maven-cache": true}"`.

**Comment by fifthposition** [comment]
This is up at https://docs-pcf-staging.cfapps.io/scdf/1-6/managing-service-instances.html#enabling-maven-artifact-caching
