### ISSUE TITLE
Missing step under installation for Maven repo configuration

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-spring-cloud-dataflow#138]
I noticed that the installation document for SCDF tile (https://docs.pivotal.io/scdf/1-6/installing.html) does not have any step describing the details to configure the Maven repo required for the tile. Should that not be included here?

**Comment by fifthposition** [comment]
See new Step 8: https://docs-pcf-staging.cfapps.io/scdf/1-6/installing.html#install
