### ISSUE TITLE
Add use of tags on User-Provided Services

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#26]
The idea is that like is currently documented at http://docs.pivotal.io/scdf/using-user-provided-service-instances.html#relational-database-service, the tags should now be added to the UPSI configuration when creating it in the background. We might not need to update the docs much except to describe what it will do behind the scenes.

depends on pivotal-cf/scs-dataflow#45

**Comment by fifthposition** [comment]
Closing, there's not much we would want to add here it turns out.
