### ISSUE TITLE
Add buildpack `-c` configuration option

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#33]
Back in the story:

https://www.pivotaltracker.com/n/projects/1562257/stories/156543502

We added the ability to set the buildpack for a specific `p-dataflow` service instance via a `-c` configuration property. So, the following should work to set the buildpack used for a specific SI:

`cf create-service p-dataflow standard mydataflow -c '{"buildpack": "my_java_custom_buildpack"}'`

Assuming that `my_java_custom_buildpack` is registered as a Java buildpack with PAS.

Unfortunately, I forgot to add a docs story for this and it got lost. Now we have customers who are trying to use this and we can provide better support.

There is currently a bug written against this functionality but that should only affect whether it works after setting it rather than stopping us from documenting the expected behavior.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-1/managing-service-instances.html#setting-the-buildpack.

There are now subsections under "Creating an Instance" on that page, for the different settings that can be set using `-c` parameters. @csterwa Let me know if you'd like us to reorganize that page another way (maybe moving the parameters to their own section or something).

![Screen Shot 2018-07-24 at 4.11.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5701b2fefd9a8c0e008e0787/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f76b7191a37cf1132a4f5e565ecc3c4a4356bcbbd671f3e57862804e0ebc843e5627973545f8b98b4abc01ba228e4883b6b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e54b53a313346ae1712431.png)
