### ISSUE TITLE
How to setup a private domain on `p-dataflow` org applications

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#43]
See Slack thread:

https://pivotal.slack.com/archives/C064Q28L9/p1538597675000100?thread_ts=1538593181.000100&cid=C064Q28L9

It seems that there is a way to use a private domain although this is a configuration at the Operator level. For the `p-dataflow` org they could use the approach documented here to use private domains for service instance backing application routes:

https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#private-domains

This doesn't affect the applications deployed into the user's space via `p-dataflow` service instances though.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-3/service-broker-and-instances.html#set-domain-for-service-instance-backing-apps.
