### ISSUE TITLE
Add docs on how to create binding credentials and access `dataflow` and `skipper` APIs

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#46]
Developers can now either bind an application to a `p-dataflow` instance or create a service-key that then will provide credentials to be used for accessing `dataflow` and `skipper` API endpoints.

GIVEN an existing `p-dataflow` instance `mydf`
AND an app `myapp` that wants to access `mydf` API endpoints
WHEN `cf bind-service myapp mydf`
THEN `myapp` will have `mydf` credentials in its `VCAP_SERVICES` environment variable

Along with the following:

GIVEN an existing `p-dataflow` instance `mydf`
WHEN `cf create-service-key mydf mykey`
THEN `cf service-key mydf mykey` will return `mydf` credentials to access `dataflow` and `skipper` APIs

**Comment by fifthposition** [comment]
Should this be its own page ("Using the REST API" or something similar)?

**Comment by csterwa** [comment]
Yes, I think that would be a good idea. Knowing that you can access the API seems like its own topic. Maybe `API Access`?

**Comment by fifthposition** [comment]
:+1: Will do that. This will also make it easier once we have sample code to link to.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-3/api-access.html.
