### ISSUE TITLE
Configure concurrent task limit on create or update

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#47]
See: https://github.com/pivotal-cf/scs-dataflow/issues/94

For more information on how this works.

**Comment by csterwa** [comment]
@fifthposition I saw this in the Done column but I don't see where the docs were updated in staging to review. Can you post the URL(s)? Thanks.

**Comment by fifthposition** [comment]
It looks like @mheath closed this one (guessing accidentally). I don’t think I did. Will reopen and hopefully that moves it back from Done (on my phone so Waffle may be difficult to access).

**Comment by fifthposition** [comment]
@csterwa Does SCDF for PCF have a default limit here? What does the tile do if a user attempts to start one too many concurrent tasks running?

**Comment by csterwa** [comment]
The default is 10

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-3/managing-service-instances.html#limiting-concurrent-tasks.
