### ISSUE TITLE
Task only instance configuration

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#49]
See: https://github.com/pivotal-cf/scs-dataflow/issues/84

For more information on how this works.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-3/managing-service-instances.html#enable-tasks-only.

**Comment by csterwa** [comment]
@fifthposition I think we should add some additional information about what is or not deployed when using each option. For `task-only` it will only deploy the relational DB and `dataflow` backing app. Thoughts?

**Comment by fifthposition** [comment]
@csterwa Updated: http://docs-pcf-staging.cfapps.io/scdf/1-3/managing-service-instances.html#enable-tasks-only
