### ISSUE TITLE
Add security role descriptions into SCDF docs

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#50]
We currently don't provide information on what level of permissions a Developer needs to interact with `p-dataflow` instances. We should add this information to our docs for Developers permissions needed in "User" space to access SCDF shell or dashboard for managing streams and tasks.

Developers with SpaceDevelopers role in the "User" space are able to read and write on `p-dataflow` instances. People with SpaceAuditor role in the "User" space as read-only.

**Comment by fifthposition** [comment]
This is up at:

* http://docs-pcf-staging.cfapps.io/scdf/1-3/getting-started.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/managing-service-instances.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/using-the-dashboard.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/using-the-shell.html
