### ISSUE TITLE
MySQL v1 to v2 migration docs

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#55]
From Thomas Fynes at Pivotal:

"do we have a doc on how to update SCDF from using pmysqlv1 to pmysqlv2? [A customer] are looking at their upgrade plan. I see scheduler should auto-update, but SCDF and SCS both explicitly call out the mysql tile & plan. SCS discusses the update process in it's docs but I cannot find anything for SCDF. I'm guessing the process would be similar where we have to go into the org running SCDF, stop the apps, run mysql-migrator, rebind them to the new mysql db and restart them?"

There are a couple of ways to migrate:

* Upgrade the SCDF for PCF tile configuration to use MySQL v2 service plans by default, apply changes and then recreate each `p-dataflow` service instance using the new configuration.
* Migrate the MySQL v1 service instances to v2 which is much more involved process.

The preferred method is to recreate each `p-dataflow` service instance with MySQL v2 backing service instances. This involves the following steps:

1. Update SCDF for PCF tile configuration to use a `p.mysql` service plan. We recommend `db-small` in most cases but this could depend on your DB usage for that service instance.
2. Apply changes in Ops Manager with the updated tile configuration
3. Create a new `p-dataflow` service instance alongside each of the existing service instances
4. Turn off any scheduled tasks or stream executions on the original instance
5. For each new `p-dataflow` service instance deploy all of the streams and tasks of the original instance
6. Turn on scheduled tasks or stream executions on the new `p-dataflow` service instance
7. Remove the original service instance

For the DB migration approach from MySQL for PCF v1 to v2, there is a more involved process than there is for SCS, docs for that found here:

https://docs.pivotal.io/spring-cloud-services/2-0/migrating-from-mysql-v1.html

In addition to migrating the DB service instance directly, there is also a need to get the new instance's binding credentials and updating the associated `p-dataflow-relational` service instance in the user's space binding credentials. The problem is that this is created with the original v1 instance and is not updated directly when migrating since it is a copy of the credentials.

Over time the answer to this is use service instance sharing but until then the process needs to include these steps.

**Comment by fifthposition** [comment]
New page is at http://docs-pcf-staging.cfapps.io/scdf/1-3/migrating-from-mysql-v1.html.
