### ISSUE TITLE
Remove all references to MySQL for PCF v1.x tile

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#59]
MySQL for PCF v1.x is no longer supported on PCF. We should remove any references, except v1 to v2 migration, and only support v2.x+.

**Comment by fifthposition** [comment]
For v1.3, this is up at:

* http://docs-pcf-staging.cfapps.io/scdf/1-3/index.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/tile-configuration.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/service-broker-and-instances.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/getting-started.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/using-user-provided-service-instances.html

For v1.2, this is up at:

* http://docs-pcf-staging.cfapps.io/scdf/1-2/index.html
* http://docs-pcf-staging.cfapps.io/scdf/1-2/tile-configuration.html
* http://docs-pcf-staging.cfapps.io/scdf/1-2/service-broker-and-instances.html
* http://docs-pcf-staging.cfapps.io/scdf/1-2/getting-started.html
* http://docs-pcf-staging.cfapps.io/scdf/1-2/using-user-provided-service-instances.html
