### ISSUE TITLE
Release notes for SCDF for PCF v1.4.0

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#62]
* Target release date of March 20, 2019
* Includes upgrade to OSS v2.0.0.RELEASE - see pivotal-cf/scs-dataflow#99

**Comment by fifthposition** [comment]
Mention #67

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-4/release-notes.html#1-4-0.

**Comment by mheath** [comment]
What username and password do I use to access the staging docs?

**Comment by fifthposition** [comment]
Mike, I sent that info in Slack.

**Comment by csterwa** [comment]
@fifthposition can we change the version to SCDF OSS `2.0.1.RELEASE`?

**Comment by fifthposition** [comment]
@csterwa Done!
