### ISSUE TITLE
Remove references to Metrics collector since it is removed in 1.4.0

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#63]
See http://docs-pcf-staging.cfapps.io/scdf/1-3/service-broker-and-instances.html#capacity-requirements

There may be in other locations within the docs.

This also includes any references to using Redis for PCF or `p-dataflow-analytics`/Redis CUPS configuration.

**Comment by fifthposition** [comment]
This is up:

* http://docs-pcf-staging.cfapps.io/scdf/1-4/index.html
* http://docs-pcf-staging.cfapps.io/scdf/1-4/tile-configuration.html
* http://docs-pcf-staging.cfapps.io/scdf/1-4/service-broker-and-instances.html
* http://docs-pcf-staging.cfapps.io/scdf/1-4/getting-started.html
* http://docs-pcf-staging.cfapps.io/scdf/1-4/managing-service-instances.html
* http://docs-pcf-staging.cfapps.io/scdf/1-4/using-user-provided-service-instances.html
* http://docs-pcf-staging.cfapps.io/scdf/1-4/viewing-service-instance-logs.html
* http://docs-pcf-staging.cfapps.io/scdf/1-4/api-access.html

all have mentions of the metrics app, the analytics service, and Redis removed.

**Comment by mheath** [comment]
We're actually using SCDF 2.0.1. I don't know if we want to mention that we're using Skipper 2.0.0 (It's basically implied.)
