### ISSUE TITLE
Describe removal of Metrics collector in update service upgrade of service instance

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#67]
Create a note about this. Upgrade will remove Metrics collector and Redis analytics service instances. This should also have been included in release notes #62.

**Comment by fifthposition** [comment]
Renamed section "Upgrading an Instance" to "Updating an Instance", and it includes the note: http://docs-pcf-staging.cfapps.io/scdf/1-4/managing-service-instances.html#updating
