### ISSUE TITLE
Skipper memory configuration per service instance

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#68]
Add section on configuring Skipper memory allocation when creating or updating service instances.

See pivotal-cf/scs-dataflow#109

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-4/managing-service-instances.html#configuring-skipper-memory-allocation

Also updated "Capacity Requirements" for Skipper's new default: http://docs-pcf-staging.cfapps.io/scdf/1-4/service-broker-and-instances.html#capacity-requirements
