### ISSUE TITLE
Clarify where to look for SCDF, SCSt, Skipper, and SCT docs

### ISSUE THREAD

**Issue by sabbyanandan** [pivotal-cf/docs-spring-cloud-dataflow#70]
As a tile-user, while using the SCDF SIs, I'm closely only looking at the tile docs, but there are no references to where to look for core features shipped in SCDF, SCSt, Skipper, and SCT.

I've seen folks wanting to know:
- how to bind an app (in a stream definition) to a specific CUPs
- how to do Kafka CUPs (maybe swap the existing rabbit with a Kafka example?)
- what CF-deployer properties are supported and how to override them

... all these are in OSS docs; the problem comes down to how would users find it. 🤔 

Suggestion:
It'd be good to clarify where to look for project-specific features. The tile shouldn't provide any duplicate content, of course. Instead, it can explain where to find them. There's something about the perojects in the ["about"](https://docs.pivotal.io/scdf/1-3/#about-oss) section that could be improved.

**Comment by fifthposition** [comment]
I think besides that "about" section, we can link to OSS documentation maybe once in a section, but not much more than that. I'm not sure how fine-grained to make the links. It seems to me that it might work to link to OSS docs each time we bring up a feature (like we do now for the dashboard and the shell), but as we aren't adding very much on top of OSS beyond security and PCF integration, it seems to me that the best approach is to point users to the OSS documentation and let them explore what relates to their use case from there.

**Comment by csterwa** [comment]
I would keep them general unless you see specific reasons to go to specific sections @fifthposition . I agree we should not link too much since this causes potential for stale links later.

**Comment by sabbytesthandle** [comment]
My observation from the support calls is that the tile docs are not useful to the developer personas. They write applications and wire them up together through SCDF. To do that, they spend the majority of their time combing through all the various OSS reference guides. 

The challenge is we have many frameworks and then SCDF. Each of them individually evolves with different versions and release cadences, and that is how they are supposed to. It is hard to cross-link both ways - we tried it already - it just doesn't work consistently (links are prone to breaking). 

All that said, a bare minimum, we can link to SCDF OSS docs. Let the developers figure their way out to the framework docs.

**Comment by sabbyanandan** [comment]
My observation from the support calls is that the tile docs are not useful to the developer personas. They write applications and wire them up together through SCDF. To do that, they spend the majority of their time combing through all the various OSS reference guides.

The challenge is we have many frameworks and then SCDF. Each of them individually evolves with different versions and release cadences, and that is how they are supposed to. It is hard to cross-link both ways - we tried it already - it just doesn't work consistently (links are prone to breaking).

All that said, a bare minimum, we can link to SCDF OSS docs. Let the developers figure their way out to the framework docs.
