### ISSUE TITLE
Replace old screenshots and update bit.ly links

### ISSUE THREAD

**Issue by sabbyanandan** [pivotal-cf/docs-spring-cloud-dataflow#71]
The [getting-started](https://docs.pivotal.io/scdf/1-3/getting-started.html) docs point to dated screenshots, and the bit.ly link is old, as well. It'd be good to keep this up-to-date because it appears the tile users are following the docs as-is and seeing differences to actuals.

**Comment by fifthposition** [comment]
This is up at

* http://docs-pcf-staging.cfapps.io/scdf/1-3/index.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/service-broker-and-instances.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/getting-started.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/managing-service-instances.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/viewing-service-instance-logs.html
* http://docs-pcf-staging.cfapps.io/scdf/1-3/using-the-shell.html

Updated existing links to OSS docs, bit.ly links, and screenshots (with accompanying text where necessary).
