### ISSUE TITLE
Update Product Snapshot for SCDF for PCF v1.4.0

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#72]
* Remove `1.0.x` & `1.1.x` rows in table
* Update versions to appropriate release versions of OSS components (SCDF OSS `v2.0.1.RELEASE` for instance)
* OM & PAS supported versions are `2.3.x-2.4.x` for now with update when `2.5.x` comes out

**Comment by fifthposition** [comment]
This is up at

* http://docs-pcf-staging.cfapps.io/scdf/1-4/#snapshot
* http://docs-pcf-staging.cfapps.io/scdf/1-4/#tile-oss-versions
