### ISSUE TITLE
Change Skipper capacity requirements for memory to 2GB in 1.4.0

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#74]
On https://docs.pivotal.io/scdf/1-3/service-broker-and-instances.html#capacity-requirements, Skipper memory for 1.4.0 will be changed to 2GB.

**Comment by fifthposition** [comment]
This is already done for v1.4 I believe: http://docs-pcf-staging.cfapps.io/scdf/1-4/service-broker-and-instances.html#capacity-requirements
