### ISSUE TITLE
Update screenshot to remove reference in v1.4 docs to Redis tile configuration

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#91]
At https://docs.pivotal.io/scdf/1-4/tile-configuration.html#configure-data-flow-server-dependent-services, the screenshot needs to be updated to remove reference to Redis service.

**Comment by fifthposition** [comment]
This is up at http://docs-pcf-staging.cfapps.io/scdf/1-4/tile-configuration.html#configure-data-flow-server-dependent-services.
