### ISSUE TITLE
Remove Redis & Metrics Collector app from architecture diagram

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-dataflow#98]
We need to update the screenshot for https://docs.pivotal.io/scdf/1-4/service-broker-and-instances.html.

**Comment by csterwa** [comment]
![SCDF for PCF Logical Overview.png](https://images.zenhubusercontent.com/5c929af08dcdbd6b61379e71/e47baa38-3836-4f42-b5c2-dcaf7babe636)

Updated diagram

**Comment by fifthposition** [comment]
This is up at https://docs-pcf-staging.cfapps.io/scdf/1-4/service-broker-and-instances.html#service-instance-architecture.
